### ISSUE TITLE
Crash in IE 11

### ISSUE THREAD

**Issue by marcovtwout** [tiblu/ep_webhooks#5]
When connecting to a pad (unauthenticated) in Internet Explorer 11 and typing something, etherpad crashes.

```
[2018-06-06 11:32:38.790] [ERROR] console - TypeError: Cannot read property 'id' of undefined
    at Object.exports.handleMessage [as hook_fn] (/opt/etherpad/etherpad-lite/node_modules/ep_webhooks/serverHooks.js:95:55)
    at normalizedhook (/opt/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:15:27)
    at hookCallWrapper (/opt/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:21:14)
    at /opt/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:88:7
    at /opt/etherpad/etherpad-lite/src/node_modules/async/lib/async.js:249:17
    at /opt/etherpad/etherpad-lite/src/node_modules/async/lib/async.js:125:13
    at Array.forEach (<anonymous>)
    at _each (/opt/etherpad/etherpad-lite/src/node_modules/async/lib/async.js:46:24)
    at async.each (/opt/etherpad/etherpad-lite/src/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/opt/etherpad/etherpad-lite/src/node_modules/async/lib/async.js:248:13)
```

`user` is undefined here: https://github.com/tiblu/ep_webhooks/blob/master/serverHooks.js#L95

**Comment by tiblu** [comment]
Thanks for the report. Can you PR this?

**Comment by marcovtwout** [comment]
Sorry, I don't have a solution and am not actively working on this project. Hopefully the bug report provides enough information to easily fix the problem.

**Comment by tiblu** [comment]
@marcovtwout Thanks a lot for your input! We'll have a look at some point.

**Comment by tiblu** [comment]
Repo is to be archived in favor of https://github.com/citizenos/ep_webhooks.
Issue moved to https://github.com/citizenos/ep_webhooks/issues/3.
